<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StreetsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('streets')->insert([
            ['name' => '1st Avenue'],
            ['name' => 'Macario Bermudez Road'],
            ['name' => '3609 Mirafuentes St.'],
            ['name' => 'Magsaysay'],
            ['name' => 'Abad Santos'],
            ['name' => 'Mahogany'],
            ['name' => 'Acacia'],
            ['name' => 'Malinawon Road'],
            ['name' => 'Agan Subdivision'],
            ['name' => 'Mangachapui'],
            ['name' => 'Agoo'],
            ['name' => 'M. B. Suaybaguio Sr.'],
            ['name' => 'Akili'],
            ['name' => 'Marek'],
            ['name' => 'Almasica'],
            ['name' => 'Mariveles'],
            ['name' => 'Almoguis'],
            ['name' => 'Marquez Road'],
            ['name' => 'Almon'],
            ['name' => 'Mayapis'],
            ['name' => 'Amherstia'],
            ['name' => 'melenders compound'],
            ['name' => 'Angelo Street'],
            ['name' => 'Mirafuentes St.'],
            ['name' => 'Apitong'],
            ['name' => 'Apokon Highway'],
            ['name' => 'Molave'],
            ['name' => 'Apokon Road'],
            ['name' => 'Nagimit'],
            ['name' => 'Narra'],
            ['name' => 'NATO'],
            ['name' => 'Arellano'],
            ['name' => 'Neem'],
            ['name' => 'Osmeña'],
            ['name' => 'Bagsikan'],
            ['name' => 'Osmeña Extension'],
            ['name' => 'Banahaw'],
            ['name' => 'Palosapis'],
            ['name' => 'Bangkal'],
            ['name' => 'Panggili'],
            ['name' => 'Biateles'],
            ['name' => 'Pereyras'],
            ['name' => 'Bonifacio'],
            ['name' => 'Pili'],
            ['name' => 'pioneer avenue'],
            ['name' => 'Bonifacio St.'],
            ['name' => 'Prk. 4 Ladia St.'],
            ['name' => 'Prk. Sampaguita II'],
            ['name' => 'C. Sotto'],
            ['name' => 'Prk. Tandang Sora-2'],
            ['name' => 'Camachili'],
            ['name' => 'Prk.13 Avocado St.'],
            ['name' => 'Camp Utley Avenue'],
            ['name' => 'Purok 3C Apokon'],
            ['name' => 'Capitol Circumferential Road'],
            ['name' => 'Purok Anahaw'],
            ['name' => 'Chinese School Drive'],
            ['name' => 'PUROK PAPAYA'],
            ['name' => 'cupcake street'],
            ['name' => 'Quezon'],
            ['name' => 'Dagang'],
            ['name' => 'Quirante I'],
            ['name' => 'Quirante II'],
            ['name' => 'Dapdap'],
            ['name' => 'Rizal'],
            ['name' => 'Davao-Agusan National Highway'],
            ['name' => 'Roxas'],
            ['name' => 'Doctor Juan Gonzales Avenue'],
            ['name' => 'Saint Celine'],
            ['name' => 'Domingo'],
            ['name' => 'Saint Claire'],
            ['name' => 'Don Ricardo Briz'],
            ['name' => 'Saint Elpedius'],
            ['name' => 'Saint Francesca'],
            ['name' => 'Saint Paul'],
            ['name' => 'Earth'],
            ['name' => 'Saint Ramon'],
            ['name' => 'Ernesto Punzalan'],
            ['name' => 'Saint Therese'],
            ['name' => 'Falcon'],
            ['name' => 'Salisi'],
            ['name' => 'First Oriental Avenue'],
            ['name' => 'Santa Cruz Avenue'],
            ['name' => 'Sison'],
            ['name' => 'Sobrecary'],
            ['name' => 'Suntan Drive'],
            ['name' => 'Surigao-Davao Coastal Road'],
            ['name' => 'Tagum - Panabo Circumferential Road'],
            ['name' => 'Tagum City Flyover'],
            ['name' => 'Gazmen Road'],
            ['name' => 'Timog Avenue'],
            ['name' => 'Gemilina'],
            ['name' => 'Tindalo'],
            ['name' => 'Guliho'],
            ['name' => 'Toog'],
            ['name' => 'Gumamela Drive'],
            ['name' => 'Tourism Complex'],
            ['name' => 'H. A. Misa'],
            ['name' => 'Tugas'],
            ['name' => 'Herminiguildo Baloyo'],
            ['name' => 'J. V. Ayala Avenue'],
            ['name' => 'Yakal'],
            ['name' => 'Kalantas'],
            ['name' => 'Yory'],
            ['name' => 'Kamagong'],
            ['name' => 'Zafra'],
            ['name' => 'Katmon'],
            ['name' => 'Dao'],
            ['name' => 'Lapu-Lapu Extension'],
            ['name' => 'Lawaan'],
            ['name' => '3rd Avenue'],
            ['name' => 'Mabini'],
            ['name' => 'Aala Rd'],
            ['name' => 'HIJO ELEM. SCHOOL'],
            ['name' => 'Mabolo']
        ]);
    }
}
